3.x
eclipse-efx/efxclipse-rt pull request #451
Opened 2022-08-11 11:56 UTC by Leorader

correcting copyright headers and about.html files for EPL V2, refs #416

2022-08-11 14:15 UTC, Leorader commented
ECA has beem signed on Aug 11, 2022

2022-08-12 06:56 UTC, tomsontom requested changes
The change causes compilation errors in the following files:
- BindingSupport.java
- TextHoverMap.java
- TextHoverMapProvider.java

2022-08-17 13:57 UTC, Leorader commented
compilation errors have been fixed now

2022-08-26 12:09 UTC, tomsontom approved these changes

2022-08-26 12:09 UTC, merged